modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="absoluteoneblock"
version="1.0.0"
displayName="Absolute One Block"
description='''A custom OneBlock experience.'''

[[dependencies.absoluteoneblock]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.absoluteoneblock]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
